/** 
 * Copyright (C) 2016 Craig Vitter - https://github.com/cvitter
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *  http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.basho.riakts.jdbc;

import java.net.UnknownHostException;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

import com.basho.riak.client.api.RiakClient;
import com.basho.riak.client.core.RiakNode;

public class Connection implements java.sql.Connection {
	
	RiakClient _client = null;
	private DatabaseMetaData _metaData = null;
	private Properties _properties = null;
	
	private static boolean IS_READ_ONLY = false;
	private static boolean AUTO_COMMIT = true;
	private static int TRANSACTION_ISOLATION = java.sql.Connection.TRANSACTION_NONE;
	private static int RESULTSET_HOLDABILITY = ResultSet.HOLD_CURSORS_OVER_COMMIT;
	
	/***
	 * Connection - instantiates a RiakClient using the connection information passed in
	 * via the url or info parameters
	 * @param url
	 * @param info
	 * @throws UnknownHostException
	 * @throws SQLException
	 */
	public Connection(String url, Properties info) throws UnknownHostException, SQLException {
		if (Utility.validateRiakUrl(url)) { // Use the URL passed in to connect
			info = Utility.getRiakPropertiesFromUrl(url);
		}
		
		_client = RiakClient.newClient(Integer.parseInt( info.getProperty("RiakPort") ), info.getProperty("RiakUrl"));
		_metaData = new com.basho.riakts.jdbc.DatabaseMetaData(url);
		_properties = info;
	} // Tested

	
	public Statement createStatement() throws SQLException {
		return createStatement(0, 0, 0);
	}  // Tested
	
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return createStatement(resultSetType, resultSetConcurrency, 0);
	}

	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		return new com.basho.riakts.jdbc.Statement(_client, resultSetType, resultSetConcurrency, resultSetHoldability);
	}
	
	
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return prepareStatement(sql, 0, 0, 0);
	}  // Tested
	
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		return prepareStatement(sql, resultSetType, resultSetConcurrency, 0);
	}
	
	public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) 
			throws SQLException {
		return new com.basho.riakts.jdbc.PreparedStatement(_client, sql, resultSetType, resultSetConcurrency, resultSetHoldability);
	}
	
	// TODO: Fix alternate prepareStatement invocations of PreparedStatement	
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return prepareStatement(sql, 0, 0, 0);
	}

	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		return prepareStatement(sql, 0, 0, 0);
	}

	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		return prepareStatement(sql, 0, 0, 0);
	}
	
	
	public void close() throws SQLException {
		_client.shutdown();
	} // Tested

	public boolean isClosed() throws SQLException {
		// Retrieves a list of nodes, if at least one of the nodes
		// is in RUNNING state returns false
		List<RiakNode> nodes = _client.getRiakCluster().getNodes();
		for (RiakNode node : nodes)
		{
		    if ( node.getNodeState().toString().equalsIgnoreCase("RUNNING") ) return false;
		}
		return true;
	} // Tested
	
	public DatabaseMetaData getMetaData() throws SQLException {
		return _metaData;
	} // Tested
	
	public boolean isReadOnly() throws SQLException {
		return IS_READ_ONLY;
	}
	
	public String getCatalog() throws SQLException {
		return null;
	} // NOTE: Catalog not yet implemented in Riak TS
	
	public int getTransactionIsolation() throws SQLException {
		return TRANSACTION_ISOLATION;
	}
	
	public int getHoldability() throws SQLException {
		return RESULTSET_HOLDABILITY;
	}
	
	public boolean getAutoCommit() throws SQLException {
		return AUTO_COMMIT;
	}
	
	public int getNetworkTimeout() throws SQLException {
		return 0;
	} // NOTE: Timeout not yet implemented in Riak TS
	
	public void setCatalog(String catalog) throws SQLException {
	} // NOTE: Not yet implemented in Riak TS
	
	public String getSchema() throws SQLException {
		return null;
	} // NOTE: Not yet implemented in Riak TS
	
	public boolean isValid(int timeout) throws SQLException {
		if (isClosed()) {
			return false;
		}
		else {
			return true;
		}
	}
	
	// TODO: Update driver to create a properties table (optionally) in Riak TS to
	// store properties if the calling application requires
	// https://github.com/cvitter/Riak-TS-JDBC-Driver/issues/18
	public void setClientInfo(String name, String value) throws SQLClientInfoException {
		if (name != null && value != null) _properties.setProperty(name, value);
	}

	public void setClientInfo(Properties properties) throws SQLClientInfoException {
		_properties = properties;
	}

	public String getClientInfo(String name) throws SQLException {
		return _properties.getProperty(name);
	}

	public Properties getClientInfo() throws SQLException {
		return _properties;
	}
	
	
	// NOTE: Following Connection methods throw UnsupportedOperationException errors
	// because the features aren't implemented in either Riak TS and/or the Driver
	
	public CallableStatement prepareCall(String sql) throws SQLException {
		throw new UnsupportedOperationException();
	} // TODO: Update if Riak TS adds stored procedures or their equivalent

	public String nativeSQL(String sql) throws SQLException {
		throw new UnsupportedOperationException();
	} // TODO: Investigate possible implementations

	public void setAutoCommit(boolean autoCommit) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void commit() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void rollback() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void setReadOnly(boolean readOnly) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void setTransactionIsolation(int level) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public SQLWarning getWarnings() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void clearWarnings() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public Map<String, Class<?>> getTypeMap() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void setHoldability(int holdability) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public Savepoint setSavepoint() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public Savepoint setSavepoint(String name) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void rollback(Savepoint savepoint) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void releaseSavepoint(Savepoint savepoint) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public CallableStatement prepareCall(String sql, int resultSetType,
			int resultSetConcurrency, int resultSetHoldability) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public Clob createClob() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public Blob createBlob() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public NClob createNClob() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public SQLXML createSQLXML() throws SQLException {
		throw new UnsupportedOperationException();
	}

	public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void setSchema(String schema) throws SQLException {
		
	}

	public void abort(Executor executor) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
		throw new UnsupportedOperationException();
	}
	
	public <T> T unwrap(Class<T> iface) throws SQLException {
		throw new UnsupportedOperationException();
	}

	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		throw new UnsupportedOperationException();
	}

}
